# Disable CI triggers, we don't want a build per merge to Master
trigger: none

resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:rhel7_prereqs_2

variables:
  _commonProps: --ci /p:ArchGroup=x64 /p:ConfigurationGroup=Debug

phases:
  - template: /eng/common/templates/phases/base.yml
    parameters:
      name: Linux
      queue:
        container: LinuxContainer
        name: Hosted Ubuntu 1604
      steps:
      - script: ./build.sh
          $(_commonProps)
        displayName: Build Sources
      - script: ./build.sh
          -test $(_commonProps) /p:SkipTests=true /p:ArchiveTests=true /p:EnableDumpling=true
        displayName: Build Tests
      - script: ./eng/common/msbuild.sh
          --warnaserror false src/upload-tests.proj
          /t:CompressRuntimeDir
          /p:ArchGroup=x64
          /p:ConfigurationGroup=Debug
          /p:TargetOS=Linux
        displayName: Compress Runtime Directory
      - script: ./eng/common/msbuild.sh
          --warnaserror false src/upload-tests2.proj
          /t:test
        displayName: Create Helix Job
        env:
          HelixSource: pr/dotnet/corefx/$(Build.SourceBranch)
          HelixBuild: $(Build.BuildNumber)
          HelixTargetQueues: Ubuntu.1604.Amd64.Open
          HelixCommand: ./RunTests.sh $HELIX_CORRELATION_PAYLOAD
          HelixAccessToken: $(BotAccount-dotnet-github-anon-kaonashi-bot-helix-token)