# Disable CI triggers, we don't want a build per merge to Master
trigger: none

resources:
  containers:
    - container: Ubuntu1604Container
      image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-e435274-20180426002255

phases:
  - template: /eng/common/templates/phases/base.yml
    parameters:
      name: Ubuntu16.04
      container: Ubuntu1604Container
      queue:
        name: Hosted Ubuntu 1604
      steps:
      - script: build.sh
          --ci /p:ArchGroup=x64 /p:ConfigurationGroup=Debug
        displayName: Build Sources
